pipeline {
    agent any
    
    environment {
        CLOUDSDK_CORE_PROJECT = 'qtravels-project' 
        GCLOUD_CREDS=credentials('gcloud-creds')
    }

    stages {
        stage('Git Checkout') {
            steps {
                echo 'Git Checkout running...'
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'f4fd4dfa-abf1-4897-870b-06da293809bb', url: 'https://github.com/vaibhavCodian/Qtravels.git']])
            }
        }
        stage('Docker Build and Push') {
            steps {
                
                sh '''
                    gcloud version
                    gcloud auth activate-service-account --key-file="$GCLOUD_CREDS"
                    gcloud artifacts repositories list
                '''

                withCredentials([file(credentialsId: 'gcloud-creds', variable: 'gcc')]) {
                    sh '''
                        gcloud auth configure-docker \
    us-central1-docker.pkg.dev --quiet
                    '''
                    
                    
                    sh 'docker build -t us-central1-docker.pkg.dev/qtravels-project/myregistry/toursapp src/.'
                    sh 'docker push us-central1-docker.pkg.dev/qtravels-project/myregistry/toursapp'
                }
    
            }
        }
        stage('GKE Build') {
            steps {
                withCredentials([file(credentialsId: 'gcloud-creds', variable: 'gcc')]) {
                    sh 'sh gcloud components install gke-gcloud-auth-plugin'
                    sh 'gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project qtravels-project'
                    sh 'kubectl get pods'
                    sh 'kubectl get services'
                    sh 'kubectl rollout restart deployment toursapp'
                }
    
            }
        }
    }
}
