pipeline {
    agent any
    
    environment {
        GKE_CLUSTER = 'cluster-1'
        GKE_ZONE = 'us-central1-c'
        GKE_NAMESPACE = 'your-namespace'
        GIT_REPO_URL = 'https://github.com/vaibhavCodian/Qtravels.git'
        ARTIFACT_REPO_URL = 'your-artifact-repo-url'
    }

    stages {
        // stage('Checkout') {
        //     // steps {
        //     //     // Checkout code from Git
        //     //     checkout([$class: 'GitSCM', branches: [[name: '*/your-branch-name']]])
        //     // }
        // }

        stage('Build and Push Docker Image') {
            steps {
                // Build Docker image
                sh "docker build -t us-central1-docker.pkg.dev/qtravels-project/myregistry/toursapp src/."
                sh "docker push us-central1-docker.pkg.dev/qtravels-project/myregistry/toursapp"
            }
        }

        stage('Deploy to GKE') {
            steps {
                // Authenticate with GKE
                script {
                    withCredentials([gcpServiceAccount('crentials.json')]) {
                        sh "gcloud auth activate-service-account --key-file=${gcp_service_account_key_file}"
                        sh "gcloud container clusters get-credentials ${GKE_CLUSTER} --zone=${GKE_ZONE}"
                    }
                }

                // Deploy to GKE using kubectl
                script {
                    sh "kubectl apply -f deployment.yml -n ${GKE_NAMESPACE}"
                    sh "kubectl apply -f service.yml -n ${GKE_NAMESPACE}"
                }
            }
        }
    }
}